# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: 'CI_Build'
    steps:
    - script: echo CI
- stage: test
  jobs:
  - job: 'Artifact'
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)'
        ArtifactName: 'drop1'
        publishLocation: 'Container'
      
  - job: 'Prod_Deploy'
    pool: server
    dependsOn: 'Artifact'
    steps:

    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'Ven41 DevOps Connection'
        UpstreamJob: 'UAT_Deploy'
