name: Build

on:
  push:
    branches: [ master ]

  workflow_dispatch:

#run-name: ${{ github.event.inputs.name }} 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: oracle

      - name: Compile
        run: mvn compile

      - name: SN Register Artifact
        uses: ServiceNow/servicenow-devops-register-artifact@v3.1.0
        with:
          devops-integration-token: ${{ secrets.SN_TOKEN }}
          instance-url: ${{ secrets.SN_URL }}
          tool-id: ${{ secrets.SN_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: ${{ github.job }}
          artifacts: '[{"name": "eli-devops", "version": "1.${{ github.run_number }}.0", "repositoryName": "${{ github.repository }}"}]'
  
                           
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: trigger deploy
  #       run: |
  #         echo Deploy
      
